repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.11
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest (quick tests)
        entry: bash -c 'if [ -f .venv/bin/pytest ]; then .venv/bin/pytest "$@"; else echo "Skipping pytest - virtual environment not found"; fi'
        language: system
        pass_filenames: false
        always_run: true
        args: ["-v", "--tb=short", "-k", "not test_cli", "--maxfail=3"]
