[project]
name = "serv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.8.1",
    "bevy>=3.0.0b2",
    "nubby>=0.1.2",
    "tramp>=2025.3.2",
]

[project.optional-dependencies]
jinja = [
    "jinja2>=3.1.6",
]
multipart = [
    "python-multipart>=0.0.20",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "uvicorn>=0.34.2",
]
